<a href="https://colab.research.google.com/github/rakshikutty0528-cmyk/Data-Analytics-using-PythonProject/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mark=np.array([80,90,70,60,50])
print(mark[1:4])

[90 70 60]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
marks=np.array([80,90,70,60])
average=np.mean(marks)
print(average)

75.0


In [ ]:
import numpy as np
salary=np.array([1000,2000,3000,4000,5000])
med=np.median(salary)
print(med)

3000.0


In [ ]:
scores = [58, 45, 73, 89, 99]

total = sum(scores)
average = total / len(scores)
highest = max(scores)
lowest = min(scores)

print("students scores:", scores)
print("Total marks:", total)
print("average marks:", average)
print("Highest marks:", highest)
print("lowest marks:", lowest)

students scores: [58, 45, 73, 89, 99]
Total marks: 364
average marks: 72.8
Highest marks: 99
lowest marks: 45
